### PR TITLE
Change certs owner to apache on redhat

### PR DESCRIPTION
**Pull request by emmetog**
This PR allows this role to run on RedHat by correctly setting the apache owner and group on redhat systems.

### CODE REVIEW

**Comment by jdauphant** [comment]
@emmetog The user is apache event if you use another HTTP server ?

**Comment by emmetog** [comment]
@jdauphant good question, I only know about apache. I do know that the httpd service (which is apache on RedHat) uses the "apache" user, but I'm not sure what nginx on RedHat uses by default.

**Comment by jdauphant** [comment]
@emmetog It's not overridable if I accept the PR and I may not work on other RedHat system in case people don't use Apache

**Comment by jdauphant** [comment]
I close it, I should have been overridable

**Pull request closed without merging**
