### PR TITLE
Combine private key and cert

### PR DESCRIPTION
**Pull request by luisico**
Adds support to haproxy and other scenarios where private key and certificate need to be in the same file.

### CODE REVIEW

**Comment by Sispheor** [comment]
Totally needed ! :)

**Comment by Sispheor** [comment]
@luisico can you rebase your branch?
@jdauphant can this be merged?

**Comment by jdauphant** [comment]
Oups 2 years :sweat_smile: I may miss this one
It need rebase, test and will be able to merge

**Comment by luisico** [comment]
Hi, will try to find time, stay tuned.

**Comment by jdauphant** [comment]
@luisico Thanks. @Sispheor just manage it in #35 
Sorry for the disturb and the delay

**Comment by luisico** [comment]
That merge will trigger the combine step every single run. That is why I there is a conditional.

**Comment by jdauphant** [comment]
If neither the key or the certificate change, the assemble task will stay green and change nothing.
It respect the idempotent of the role normally.
Do I miss something?

**Comment by luisico** [comment]
I think you might be correct, but I haven't test all cases. I did that 2 years ago for a reason, but honestly, can't remember anymore. I think it had to do with changing back and forth from local files or data to generated certs. One of those "paths" did not update the certs. But that should be another issue and as long as privkey and cert are updated correctly assemble should take care of it. Best, Luis

**Comment by Sispheor** [comment]
I've tested, the assemble module is idempotent. So it's ok guys :)

**Pull request closed without merging**
